spring:
  # 生产环境的数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user-center
    username: root
    password: 123456
  # session 失效时间
  session:
    timeout: 86400
